### ISSUE TITLE
Fiddle demo not working

### ISSUE THREAD

**Issue by airandfingers** [Zertz/bootstrap-horizon#4]
Hi, I noticed that the preview at https://jsfiddle.net/azu9mf8d/3 is no longer working.

The bootstrap-horizon.css file is 404ing, but when I removed it and added an external resource with the URL https://raw.githubusercontent.com/Zertz/bootstrap-horizon/master/src/bootstrap-horizon.css, it still didn't work.

By the way, thanks for your work on this project! It fit my needs very nicely, and the 90% total width instead of 100% is a very nice touch.

**Comment by Zertz** [comment]
Thanks for reporting this issue! I'll look into it
